---
- hosts: pihole
  become: true
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: Execute pihole disable 15 min
      shell: pihole disable 15m
